import { useEffect, useMemo, useState } from "react"
import { Alert, AlertDescription, AlertTitle } from "@moirasia/ui-react/components/alert"
import { Badge } from "@moirasia/ui-react/components/badge"
import { Button } from "@moirasia/ui-react/components/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@moirasia/ui-react/components/card"
import { ChartContainer, ChartTooltip, Line, LineChart, XAxis, YAxis, type ChartConfig } from "@moirasia/ui-react/components/chart"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@moirasia/ui-react/components/dialog"
import { Switch } from "@moirasia/ui-react/components/switch"
import { Cpu, Gauge, MemoryStick, Pause, Play, Settings } from "@moirasia/ui-react/lib/icons"
import type { Availability, ExithibitionEvent, ExithibitionSnapshot, HardwareSample, HistoryRange, LayoutComponent } from "../shared/contracts"
import { DesktopAppShell, DesktopContentHeader, DesktopPage, useProductAppearance } from '@moirasia/desktop-shell/react'

const chartConfig = { value: { label: "Utilization", color: "var(--exithibition-color-warm)" } } satisfies ChartConfig
export function App() {
  const [appearance, setAppearance] = useProductAppearance(window.desktopShell)
  const [snapshot, setSnapshot] = useState<ExithibitionSnapshot>()
  const [history, setHistory] = useState<readonly HardwareSample[]>([])
  const [range, setRange] = useState<HistoryRange>("5m")
  const [selection, setSelection] = useState("overview")
  const [error, setError] = useState("")
  const [settingsOpen, setSettingsOpen] = useState(false)
  useEffect(() => { let active = true; void window.exithibition.getSnapshot().then((value) => active && setSnapshot(value)).catch((reason) => active && setError(message(reason))); const unsubscribe = window.exithibition.onEvent((event) => { if (!active) return; applyEvent(event, setSnapshot, setHistory, setError) }); return () => { active = false; unsubscribe() } }, [])
  useEffect(() => { void window.exithibition.getHistory(range).then(setHistory).catch((reason) => setError(message(reason))) }, [range, snapshot?.sample.id])
  const toggleSampling = () => { if (snapshot) void window.exithibition.setSampling(!snapshot.state.sampling).then((state) => setSnapshot((current) => current ? { ...current, state } : current)).catch((reason) => setError(message(reason))) }
  return <DesktopAppShell product="Exithibition" appearance={appearance} onAppearanceChange={setAppearance}><DesktopPage width="wide" className="dashboard">
    {!snapshot ? <div className="loading" role="status">Detecting hardware…{error && <span>{error}</span>}</div> : <>
    <DesktopContentHeader title="Hardware telemetry" description={`${snapshot.profile.marketingName} · ${snapshot.profile.chipName}`} status={<Badge variant={snapshot.state.sampling ? "secondary" : "outline"}>{snapshot.state.sampling ? "Sampling · 1 Hz" : "Paused"}</Badge>} actions={<><Button size="icon" aria-label={snapshot.state.sampling ? "Pause sampling" : "Resume sampling"} onClick={toggleSampling}>{snapshot.state.sampling ? <Pause /> : <Play />}</Button><Button size="icon" aria-label="Telemetry settings" onClick={() => setSettingsOpen(true)}><Settings /></Button></>} />
    {error && <Alert variant="destructive"><AlertTitle>Telemetry error</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
    {!snapshot.layout.isCurated && <Alert><AlertTitle>Adaptive hardware layout</AlertTitle><AlertDescription>No curated layout exists for {snapshot.profile.modelIdentifier}; Exithibition generated a topology from detected hardware.</AlertDescription></Alert>}
    <section className="workspace"><Card className="schematic-card"><CardHeader><div><Badge variant="outline">LIVE BOARD</Badge><CardTitle>{snapshot.profile.modelIdentifier}</CardTitle></div><div className="legend"><span><i className="cool" />Idle</span><span><i className="warm" />Active</span><span><i className="hot" />High</span></div></CardHeader><CardContent><HardwareSchematic snapshot={snapshot} selection={selection} select={setSelection} /></CardContent></Card><Inspector snapshot={snapshot} history={history} selection={selection} range={range} setRange={setRange} /></section>
    <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent><DialogHeader><DialogTitle>Experimental sensors</DialogTitle><DialogDescription>Unsupported AppleSMC and IOAccelerator readings can disappear or be inaccurate on this hardware.</DialogDescription></DialogHeader><div className="setting-row"><div><strong>Temperature, fan, and GPU sensors</strong><small>Preference is stored in com.local.Exithibition.</small></div><Switch aria-label="Experimental sensors" checked={snapshot.state.experimentalSensorsEnabled} onCheckedChange={(enabled) => void window.exithibition.setExperimentalSensorsEnabled(enabled).then((state) => setSnapshot((current) => current ? { ...current, state } : current)).catch((reason) => setError(message(reason)))} /></div><DialogFooter><Button onClick={() => setSettingsOpen(false)}>Done</Button></DialogFooter></DialogContent></Dialog></>}
  </DesktopPage></DesktopAppShell>
}

function applyEvent(event: ExithibitionEvent, setSnapshot: React.Dispatch<React.SetStateAction<ExithibitionSnapshot | undefined>>, setHistory: React.Dispatch<React.SetStateAction<readonly HardwareSample[]>>, setError: (value: string) => void) { if (event.type === "snapshot") setSnapshot(event.payload); if (event.type === "sample") { setSnapshot((current) => current ? { ...current, sample: event.payload } : current); setHistory((current) => [...current.slice(-43_199), event.payload]) } if (event.type === "state") setSnapshot((current) => current ? { ...current, state: event.payload } : current); if (event.type === "error") setError(event.payload.message) }

function HardwareSchematic({ snapshot, selection, select }: { snapshot: ExithibitionSnapshot; selection: string; select: (value: string) => void }) {
  const width = 1000, height = width / snapshot.layout.aspectRatio
  return <div className="schematic-wrap"><svg className="schematic" viewBox={`0 0 ${width} ${height}`} role="group" aria-label={`Interactive hardware schematic for ${snapshot.profile.chipName}`}>{snapshot.layout.components.map((component) => { const value = componentValue(component, snapshot.sample); const x = component.frame.x * width, y = component.frame.y * height, w = component.frame.width * width, h = component.frame.height * height; const selectable = component.selection !== null; return <g key={component.id} role={selectable ? "button" : undefined} tabIndex={selectable ? 0 : undefined} aria-label={`${component.label}: ${formatPercent(value)}`} aria-pressed={selectable ? selection === component.selection : undefined} className={`hardware-component kind-${component.kind} ${selection === component.selection ? "selected" : ""}`} style={{ "--load": String(value) } as React.CSSProperties} onClick={() => component.selection && select(component.selection)} onKeyDown={(event) => { if (component.selection && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); select(component.selection) } }}><rect x={x} y={y} width={w} height={h} rx={Math.min(8, w * .08)} /><rect className="load" x={x} y={y + h * (1 - value)} width={w} height={h * value} rx={Math.min(8, w * .08)} /><text x={x + w / 2} y={y + h / 2} dominantBaseline="middle" textAnchor="middle">{shortLabel(component)}</text></g> })}</svg><ul className="sr-only">{snapshot.layout.components.map((component) => <li key={component.id}>{component.label}: {formatPercent(componentValue(component, snapshot.sample))}</li>)}</ul></div>
}

function Inspector({ snapshot, history, selection, range, setRange }: { snapshot: ExithibitionSnapshot; history: readonly HardwareSample[]; selection: string; range: HistoryRange; setRange: (range: HistoryRange) => void }) {
  const presentation = metric(snapshot.sample, selection)
  const data = useMemo(() => history.map((sample) => ({ time: new Date(sample.capturedAt).toLocaleTimeString([], { minute: "2-digit", second: "2-digit" }), value: metric(sample, selection).number * 100 })), [history, selection])
  return <Card className="inspector"><CardHeader><Badge variant={presentation.experimental ? "destructive" : "outline"}>{presentation.status}</Badge><CardTitle>{presentation.title}</CardTitle><CardDescription>{presentation.source}</CardDescription></CardHeader><CardContent><div className="primary-reading"><strong>{presentation.value}</strong><span>{presentation.detail}</span></div><div className="range-row"><span>SESSION</span><select aria-label="Chart range" value={range} onChange={(event) => setRange(event.target.value as HistoryRange)}>{["1m", "5m", "15m", "1h", "Session"].map((value) => <option key={value}>{value}</option>)}</select></div><ChartContainer config={chartConfig} className="metric-chart"><LineChart data={data}><XAxis dataKey="time" tickLine={false} axisLine={false} minTickGap={30} /><YAxis domain={[0, 100]} hide /><ChartTooltip /><Line type="monotone" dataKey="value" stroke="var(--color-value)" strokeWidth={2} dot={false} isAnimationActive={false} /></LineChart></ChartContainer><dl className="facts"><div><dt>Availability</dt><dd>{presentation.status}</dd></div><div><dt>Source</dt><dd>{presentation.source}</dd></div><div><dt>Samples</dt><dd>{history.length.toLocaleString()} in memory</dd></div></dl>{presentation.experimental && <Alert variant="destructive"><AlertDescription>Experimental readings use unsupported interfaces and may be inaccurate.</AlertDescription></Alert>}</CardContent></Card>
}

function componentValue(component: LayoutComponent, sample: HardwareSample) { if (component.kind === "cpuCore") return clamp(sample.cpuLoads[component.tileIndex ?? -1]?.value ?? 0); if (component.kind === "gpuCore" || component.kind === "gpu") return clamp(sample.gpu.value?.deviceUtilization ?? sample.gpu.value?.rendererUtilization ?? 0); if (component.kind === "memory") return memoryUtilization(sample.memory); if (component.kind === "storage") return clamp(((sample.storage.value?.readBytesPerSecond ?? 0) + (sample.storage.value?.writeBytesPerSecond ?? 0)) / (5 * 1024 ** 3)); if (component.kind === "battery") return clamp(sample.battery.value?.chargeFraction ?? 0); if (component.kind === "fan") { const fan = sample.fans.value?.[component.tileIndex ?? 0]; return clamp(fan ? fan.rpm / (fan.maximumRPM ?? 7000) : 0) } return 0.08 }
function metric(sample: HardwareSample, selection: string) { if (selection.startsWith("cpuCore:")) { const index = Number(selection.split(":")[1]); return present(`CPU core ${index + 1}`, sample.cpuLoads[index] ?? { status: "unavailable", value: null, source: null, reason: "Core is unavailable" }, "Per-core utilization") } if (selection === "gpu") return present("GPU", mapAvailability(sample.gpu, (value) => value.deviceUtilization ?? value.rendererUtilization ?? value.tilerUtilization ?? 0), "Driver-reported engine load"); if (selection === "memory") return present("Unified memory", mapAvailability(sample.memory, (value) => value.totalBytes ? (value.activeBytes + value.wiredBytes + value.compressedBytes) / value.totalBytes : 0), sample.memory.value ? `${formatBytes(sample.memory.value.totalBytes)} total` : "Awaiting reading"); if (selection === "storage") return present("Storage", mapAvailability(sample.storage, (value) => clamp((value.readBytesPerSecond + value.writeBytesPerSecond) / (5 * 1024 ** 3))), sample.storage.value ? `${formatRate(sample.storage.value.readBytesPerSecond)} read · ${formatRate(sample.storage.value.writeBytesPerSecond)} write` : "Awaiting baseline"); if (selection === "network") return present("Network", mapAvailability(sample.network, (value) => clamp((value.receivedBytesPerSecond + value.sentBytesPerSecond) / (1024 ** 3))), sample.network.value ? `${formatRate(sample.network.value.receivedBytesPerSecond)} down · ${formatRate(sample.network.value.sentBytesPerSecond)} up` : "Awaiting baseline"); if (selection === "battery") return present("Battery", mapAvailability(sample.battery, (value) => value.chargeFraction), sample.battery.value?.isCharging ? "Charging" : "On battery"); if (selection === "thermal") { const state = sample.thermalState.value ?? "unavailable"; const number = ({ nominal: .1, fair: .4, serious: .75, critical: 1 } as Record<string, number>)[state] ?? 0; return { title: "Thermal state", number, value: state, detail: "System thermal pressure", status: sample.thermalState.status, source: sample.thermalState.source ?? sample.thermalState.reason ?? "Unavailable", experimental: sample.thermalState.status === "experimental" } } const values = sample.cpuLoads.flatMap((load) => load.value ?? []); const average = values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0; return { title: "System overview", number: average, value: formatPercent(average), detail: `${sample.cpuLoads.length} CPU cores`, status: "available", source: "Host processor counters", experimental: false } }
function present(title: string, availability: Availability<number>, detail: string) { const number = clamp(availability.value ?? 0); return { title, number, value: availability.value == null ? "—" : formatPercent(number), detail, status: availability.status, source: availability.source ?? availability.reason ?? "Unavailable", experimental: availability.status === "experimental" } }
function mapAvailability<T>(availability: Availability<T>, transform: (value: T) => number): Availability<number> { return { ...availability, value: availability.value == null ? null : transform(availability.value) } }
function memoryUtilization(value: HardwareSample["memory"]) { const memory = value.value; return memory?.totalBytes ? clamp((memory.activeBytes + memory.wiredBytes + memory.compressedBytes) / memory.totalBytes) : 0 }
function shortLabel(component: LayoutComponent) { if (component.kind === "cpuCore") return `C${(component.tileIndex ?? 0) + 1}`; if (component.kind === "gpuCore") return `G${(component.tileIndex ?? 0) + 1}`; return component.label.length > 12 ? component.kind.toUpperCase() : component.label }
function clamp(value: number) { return Number.isFinite(value) ? Math.min(1, Math.max(0, value)) : 0 }
function formatPercent(value: number) { return new Intl.NumberFormat(undefined, { style: "percent", maximumFractionDigits: 0 }).format(clamp(value)) }
function formatBytes(value: number) { return new Intl.NumberFormat(undefined, { style: "unit", unit: "gigabyte", maximumFractionDigits: 1 }).format(value / 1024 ** 3) }
function formatRate(value: number) { return `${new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(value)}B/s` }
function message(error: unknown) { return error instanceof Error ? error.message : String(error) }
