export type Availability<T> = { status: "available" | "experimental" | "unavailable"; value: T | null; source: string | null; reason: string | null }
export type MachineProfile = { modelIdentifier: string; marketingName: string; chipName: string; cpuGroups: readonly { id: string; name: string; kind: string; coreIDs: readonly number[] }[]; gpuCoreCount: number | null; unifiedMemoryBytes: number; storage: readonly { id: string; name: string; capacityBytes: number }[]; hasBattery: boolean; capabilities: { hasBattery: boolean; hasMetalGPU: boolean; supportsSMC: boolean; supportsIOAccelerator: boolean } }
export type LayoutComponent = { id: string; kind: string; label: string; frame: { x: number; y: number; width: number; height: number }; selection: string | null; tileIndex: number | null; sharesAggregateTelemetry: boolean }
export type ResolvedLayout = { modelIdentifier: string; aspectRatio: number; components: readonly LayoutComponent[]; isCurated: boolean }
export type MemoryMetrics = { activeBytes: number; wiredBytes: number; compressedBytes: number; cachedBytes: number; totalBytes: number }
export type HardwareSample = { id: number; monotonicTime: number; capturedAt: string; cpuLoads: readonly Availability<number>[]; gpu: Availability<{ deviceUtilization: number | null; rendererUtilization: number | null; tilerUtilization: number | null; allocatedMemoryBytes: number | null; inUseMemoryBytes: number | null }>; memory: Availability<MemoryMetrics>; storage: Availability<{ readBytesPerSecond: number; writeBytesPerSecond: number }>; network: Availability<{ receivedBytesPerSecond: number; sentBytesPerSecond: number; interfaceNames: readonly string[] }>; battery: Availability<{ chargeFraction: number; isCharging: boolean; timeRemainingMinutes: number | null }>; thermalState: Availability<string>; temperatureZones: Availability<readonly { id: string; name: string; celsius: number }[]>; fans: Availability<readonly { id: string; name: string; rpm: number; maximumRPM: number | null }[]> }
export type RuntimeState = { sampling: boolean; experimentalSensorsEnabled: boolean }
export type ExithibitionSnapshot = { profile: MachineProfile; layout: ResolvedLayout; sample: HardwareSample; state: RuntimeState }
export type HistoryRange = "1m" | "5m" | "15m" | "1h" | "Session"
export type ExithibitionEvent = { type: "snapshot"; payload: ExithibitionSnapshot } | { type: "sample"; payload: HardwareSample } | { type: "state"; payload: RuntimeState } | { type: "error"; payload: { message: string } }
export type ExithibitionAPI = { getSnapshot(): Promise<ExithibitionSnapshot>; getHistory(range: HistoryRange): Promise<readonly HardwareSample[]>; setSampling(enabled: boolean): Promise<RuntimeState>; setExperimentalSensorsEnabled(enabled: boolean): Promise<RuntimeState>; onEvent(listener: (event: ExithibitionEvent) => void): () => void }

export function isHistoryRange(value: unknown): value is HistoryRange { return typeof value === "string" && ["1m", "5m", "15m", "1h", "Session"].includes(value) }
export function isExithibitionEvent(value: unknown): value is ExithibitionEvent { if (!record(value) || !exact(value, ["type", "payload"]) || !record(value.payload) || typeof value.type !== "string") return false; return ["snapshot", "sample", "state", "error"].includes(value.type) }
export function isNativeMessage(value: unknown): value is { type: "event"; event: string; payload: unknown } | { type: "response"; id: string; ok: boolean; result?: unknown; error?: { code: string; message: string } } { if (!record(value) || typeof value.type !== "string") return false; if (value.type === "event") return exact(value, ["type", "event", "payload"]) && typeof value.event === "string"; if (value.type === "response") return typeof value.id === "string" && typeof value.ok === "boolean" && Object.keys(value).every((key) => ["type", "id", "ok", "result", "error"].includes(key)); return false }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) }
function exact(value: Record<string, unknown>, keys: readonly string[]) { return Object.keys(value).length === keys.length && keys.every((key) => key in value) }
