import { AppearanceControl } from '@moirasia/desktop-shell/react'
import type { Appearance } from '@moirasia/desktop-shell'
import { Button } from '@moirasia/ui-react/components/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@moirasia/ui-react/components/card'
import { Separator } from '@moirasia/ui-react/components/separator'
import { Switch } from '@moirasia/ui-react/components/switch'
import type { useController } from '../controller'
function Row({ label, description, children }: { label: string; description: string; children: React.ReactNode }) { return <div className="setting-row"><div><strong>{label}</strong><small>{description}</small></div>{children}</div> }
export function SettingsScreen({ controller }: { controller: ReturnType<typeof useController> }): React.JSX.Element {
  const values = controller.snapshot.appearances.values; const unique = new Set(Object.values(values)); const mixed = unique.size > 1; const allValue = (mixed ? 'system' : [...unique][0]) as Appearance
  return <section className="controller-page" aria-labelledby="settings-heading"><p className="eyebrow">PREFERENCES</p><h1 id="settings-heading">Settings</h1><Card><CardHeader><CardTitle>Appearance</CardTitle><CardDescription>Changes apply live to every running application.</CardDescription></CardHeader><CardContent><Row label="All apps" description="Set Moirasia and all standalone apps together."><AppearanceControl label="All apps appearance" value={allValue} mixed={mixed} onChange={controller.setAllAppearances}/></Row>{(['moirasia','amove','vox','exithibition'] as const).map((id) => <div key={id}><Separator/><Row label={id === 'exithibition' ? 'Exithibition' : id[0]!.toUpperCase()+id.slice(1)} description="Independent appearance setting."><AppearanceControl label={`${id} appearance`} value={values[id]} onChange={(value) => controller.setAppearance(id, value)}/></Row></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Login items</CardTitle><CardDescription>Each application owns its independent macOS login item.</CardDescription></CardHeader><CardContent><Row label="Moirasia" description="Open the controller when you sign in."><Switch aria-label="Launch Moirasia at login" checked={controller.settings.launchAtLogin} onCheckedChange={controller.setLaunchAtLogin}/></Row>{controller.snapshot.applications.map((application) => <div key={application.id}><Separator/><Row label={application.label} description={!application.installed ? 'Install the app to manage its login item.' : application.loginItem?.status === 'requires-approval' ? 'Approval is required in System Settings.' : 'Open this app when you sign in.'}><Switch aria-label={`Launch ${application.label} at login`} disabled={!application.installed || !!application.busy} checked={application.loginItem?.openAtLogin ?? !!controller.settings.pendingLoginItems[application.id]} onCheckedChange={(enabled) => controller.setLoginItem(application.id, enabled)}/></Row></div>)}<Separator/><div className="settings-link"><Button variant="outline" size="sm" onClick={controller.openLoginItemsSettings}>Open Login Items Settings</Button></div></CardContent></Card></section>
}
